#!/usr/bin/env ruby

# Makes every customer_entity's email-address record a newsletter_subscriber's
# subscriber_mail, too. (Magento 2.1.9)

# Copyright 2017 Felix Wolfsteller, licensed under the GPLv3+.

require 'mysql2'

if ARGV.count != 4 && ARGV.count != 5
  STDERR.puts "Need to be called as '#{$PROGRAM_NAME} <host> <user> <pass> <dbname> [one-at-a-time]'"
  exit 1
end

one_at_a_time = ARGV.count == 5

host, user, pass, dbname = ARGV

client = Mysql2::Client.new(host: host, username: user, password: pass, database: dbname)

unsubscribed_mail_query = "SELECT * "\
                          "  FROM customer_entity "\
                          "  WHERE email NOT IN "\
                          "    (SELECT subscriber_email FROM newsletter_subscriber);"

results = client.query unsubscribed_mail_query

puts "#{results.count} subscribers to add"

results.each do |row|
  customer_id = "\"#{row['entity_id']}\""
  mail        = "\"#{row['email']}\""
  new_subscriber_query = "INSERT into newsletter_subscriber (store_id, customer_id, subscriber_email, subscriber_status, subscriber_confirm_code) "\
                         "            VALUES                (1    ,    #{customer_id}, #{mail}, 1, \"8ppx6xp29edf503l9jz9lqkfheffpt0s\");"
  if one_at_a_time
    puts new_subscriber_query
    client.query new_subscriber_query
    exit 0
  end

  client.query new_subscriber_query
end

exit 0
